// import courseImg from '../img/courses.png';
// import tutorImg from '../img/author.png';
import video from "./script.mp4";
import video2 from "./video2.mp4";
import video3 from "./video3.mp4";

const CourseData = [
  {
    id: "c1",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
      { id: "c13", title: "lecture 3" },
      { id: "c14", title: "lecture 4" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "4",
    courseDuration: "4 hrs 25 mins",
    courseDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    courseLevel: "secondary",
    courseLanguage: "Urdu",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web Development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c2",

    courseTrailer: ` ${video2} `,
    coursePoster:
      "https://www.seekpng.com/png/full/43-431988_clip-art-stack-of-books-image-of-stack.png",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
      { id: "c13", title: "lecture 1" },
      { id: "c14", title: "lecture 2" },
      { id: "c15", title: "lecture 1" },
      { id: "c16", title: "lecture 2" },
      { id: "c17", title: "lecture 1" },
      { id: "c18", title: "lecture 2" },
      { id: "c19", title: "lecture 1" },
      { id: "c20", title: "lecture 2" },
      { id: "c21", title: "lecture 1" },
      { id: "c22", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseLevel: "All",
    courseLanguage: "English",
    courseDuration: "2 hrs 24 mins",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Development",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c3",

    courseTrailer: ` ${video3} `,
    coursePoster:
      "https://cdn.pixabay.com/photo/2016/02/16/21/07/books-1204029_960_720.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    courseLevel: "All",
    courseLanguage: "English",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c4",

    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c5",

    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c6",

    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c7",

    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c8",

    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Simmons",
    courseCategory: "Web development",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c9",

    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c10",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c11",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c12",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c13",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c14",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c15",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c16",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Data visualisation and statistical analysis",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c17",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "dataanalytics",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c18",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c19",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c20",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "web",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Zulkifal",
    courseCategory: "Data Analytics",
    courseTitle: "Basics of Web Development & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c21",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c22",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c23",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c24",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c25",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c26",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c27",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c28",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c29",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c30",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c31",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Madeha Mushtaq",
    courseCategory: "Engineering",
    courseTitle: "Basics of Engineering & Coding",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c32",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c33",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c34",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c344",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c35",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c36",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c37",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c38",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c39",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c40",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c41",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "design",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
  {
    id: "c42",
    courseTrailer: ` ${video} `,
    coursePoster: "https://www.linkpicture.com/q/courses.jpg",

    courseVideos: [
      { id: "c11", title: "lecture 1" },
      { id: "c12", title: "lecture 2" },
    ],
    courseInstructors: [
      {
        id: "i1",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Front end developer",
      },
      {
        id: "i2",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
      {
        id: "i3",
        tutorImg: "https://www.linkpicture.com/q/author.jpg",
        tutorName: "Simmons",
        skills: "Backend end developer",
      },
    ],
    courseDuration: "4 hrs 25 mins",
    category: "engineering",
    courseImg: "https://www.linkpicture.com/q/courses.jpg",
    price: "Free",
    rating: "5",
    tutorImg: "https://www.linkpicture.com/q/author.jpg",
    tutorName: "Eng. Sumayyea Salahuddin",
    courseCategory: "Web Design",
    courseTitle: "Basics of Web Design & How to use AdobeXD",
    totalStudent: "40 students",
    courseCertification: "no",
  },
];

export default CourseData;
